language: python
python:
  - "3.5"
  - "3.6"
env:
  - DJANGO_SETTINGS_MODULE=app.settings.test
script:
  - pip install -r requirements-test.txt
  - coverage run ./manage.py test
after_success:
  - coveralls
dist: trusty
jobs:
  include:
    - stage: test
      script: echo flake8
