version: '3'
services:

  worker:
    build:
      context: .
      dockerfile: ./dependencies/Dockerfile-worker
    environment:
    - DJANGO_SETTINGS_MODULE=apsp.settings.staging
    - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    - DATABASE_URL=postgres://postgres:postgres@db:5432/ao-dev
    env_file:
    - env.list
    depends_on:
    - db
    - rabbitmq
  web:
    build:
      context: .
      dockerfile: ./dependencies/Dockerfile-app
    environment:
    - DJANGO_SETTINGS_MODULE=app.settings.staging
    - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    - DATABASE_URL=postgres://postgres:postgres@db:5432/ao-dev
    env_file:
    - env.list
    ports:
    - 8001:8000
    depends_on:
    - db
    - rabbitmq

  db:
    build:
      context: ./dependencies
      dockerfile: Dockerfile-db
    environment:
    - POSTGRES_DB=ao-dev
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    ports:
    - 5432:5432

  rabbitmq:
    image: rabbitmq:3-management
    ports:
    - 8080:15672

